### ISSUE TITLE
Dependence management

### ISSUE THREAD

**Issue by canhlinh** [mkenney/go-chrome#105]
Could you add a dependence management for this project  ? Such as `dep` `glide`

**Comment by mkenney** [comment]
Hi! Sorry I missed your message, it's been a hectic week. This package's dependencies are managed by `dep`, the config and lock files are [`Gopkg.toml`](https://github.com/mkenney/go-chrome/blob/master/Gopkg.toml) and [`Gopkg.lock`](https://github.com/mkenney/go-chrome/blob/master/Gopkg.lock)... is that what you're looking for?

**Comment by canhlinh** [comment]
Sorry, You are right.
