### ISSUE TITLE
logo proposal for go-chrome

### ISSUE THREAD

**Issue by anablog** [mkenney/go-chrome#108]
Hello a pleasure in greeting you, I wanted to introduce myself I am Ana Medina Graphic Web Designer, I am very interested in your new open source project for me it would be a pleasure to provide my services as a designer and collaborate without commitments, You require a new logo for your brand I can help him?

I well be pleased to collaborate with you.

**Comment by mkenney** [comment]
Hello! Thank you for reaching out to me. I would be happy to collaborate with you on logo ideas and help you build your portfolio.

This project is written in Golang so I would like to stay with logo that incorporates the [gopher mascot](https://blog.golang.org/gopher). The main focus of this project is manipulating web browsers which is why the current logo is holding a computer.

Please let me know your thoughts on a logo. Thank you!

**Comment by anablog** [comment]
Great, is to say that you want to keep this mascot but you must adapt the
thematic of web, more simplified and with a computer?

The mascot seems very good, of course it could be vectorized and make an
asymmetrical logo.

2018-07-28 14:04 GMT-04:00 Michael Kenney <notifications@github.com>:

**Comment by mkenney** [comment]
I'm open to any ideas. I do want to incorporate the gopher mascot and try to make it clear that this project is used with web browsers.

An original work using a [Creative Commons license](https://creativecommons.org/licenses/by/4.0/) would be preferred. The current image was generated using an online tool called [Gopherize Me](https://gopherize.me/gopher/255e20ee48c85f3b4701446e2513c100f22129f3).

**Comment by anablog** [comment]
Perfect, I will prepare proposals
Has any requirement is specific color, shape?
I know that I will use the gopher pet, only that I will adapt it for the
website.

2018-07-29 15:54 GMT-04:00 Michael Kenney <notifications@github.com>:

**Comment by mkenney** [comment]
This is probably the best reference for the mascot look and feel: https://github.com/ashleymcnamara/gophers

But there are [lots of images](https://www.google.com/search?q=golang+gopher+mascot&source=lnms&tbm=isch&sa=X&ved=0ahUKEwi1x_2y89jcAhUHeKwKHTzJAa0Q_AUICigB&biw=1600&bih=1467) to refer to. 

I don't have any specific requirements, only that it communicates that this software is used to control web browsers using the [Chrome DevTools Protocol](https://chromedevtools.github.io/devtools-protocol/) which let programmers write programs that control web browsers.

**Comment by mkenney** [comment]
I'm going to close this issue. Please feel free to let me know if you become interested again.
