### ISSUE TITLE
Open tabs list memory leak?

### ISSUE THREAD

**Issue by ozburo** [mkenney/go-chrome#110]
### What version of `go-chrome` are you using (tag, hash, etc.)?

Running v1.0.0 RC 3

### What behavior do you expect? What are you trying to accomplish?

I like to keep my main browser process/connection open and open/close tabs
for each job I have.

### What behavior are you experiencing instead?

When you close the tab, it _is_ closed, but a reference to it is kept on the main
Chrome struct `tabs []*Tab` list
https://github.com/mkenney/go-chrome/blob/master/tot/chrome.chromium.go#L52

### How can this behavior be reproduced?

Essentially if you keep opening/closing a bunch of Tabs, this list will continue to grow...

I'm pretty sure all we need to do is remove the reference on Tab.Close(), but I wanted to open this
issue incase there's something else that needs to be done, or there's a reason for this behaviour etc.

Cheers, again!

**Comment by mkenney** [comment]
No, there's no good reason for that :)

I think you're right, the tab needs to be removed from the list on close if the [`Chromium().Query()`](https://github.com/mkenney/go-chrome/blob/master/tot/tab.tabber.go#L79) call doesn't return an error.

Feel free to open a PR to do that, or I will try to take a look in the next day or two.

**Comment by mkenney** [comment]
This change has been merged, please let me know if you notice any other issues.
