### ISSUE TITLE
Getting build errors.

### ISSUE THREAD

**Issue by vbisbest** [mkenney/go-chrome#137]
Using master branch, I am unable to build the simple sample.   Getting these errors:

# github.com/mkenney/go-chrome/codes
../../../go/pkg/mod/github.com/mkenney/go-chrome@v1.0.0-rc8/codes/codes.go:101:2: undefined: errors.Codes
../../../go/pkg/mod/github.com/mkenney/go-chrome@v1.0.0-rc8/codes/codes.go:101:28: undefined: errors.ErrCode
../../../go/pkg/mod/github.com/mkenney/go-chrome@v1.0.0-rc8/codes/codes.go:102:2: undefined: errors.Codes
../../../go/pkg/mod/github.com/mkenney/go-chrome@v1.0.0-rc8/codes/codes.go:102:24: undefined: errors.ErrCode
../../../go/pkg/mod/github.com/mkenney/go-chrome@v1.0.0-rc8/codes/codes.go:103:2: undefined: errors.Codes
../../../go/pkg/mod/github.com/mkenney/go-chrome@v1.0.0-rc8/codes/codes.go:103:24: undefined: errors.ErrCode
../../../go/pkg/mod/github.com/mkenney/go-chrome@v1.0.0-rc8/codes/codes.go:105:2: undefined: errors.Codes
../../../go/pkg/mod/github.com/mkenney/go-chrome@v1.0.0-rc8/codes/codes.go:105:39: undefined: errors.ErrCode
../../../go/pkg/mod/github.com/mkenney/go-chrome@v1.0.0-rc8/codes/codes.go:106:2: undefined: errors.Codes
../../../go/pkg/mod/github.com/mkenney/go-chrome@v1.0.0-rc8/codes/codes.go:106:39: undefined: errors.ErrCode
../../../go/pkg/mod/github.com/mkenney/go-chrome@v1.0.0-rc8/codes/codes.go:106:39: too many errors

**Comment by Mindgamesnl** [comment]
Bump this

**Comment by mkenney** [comment]
Hi, sorry it took me so long to get to this. I have converted the package from `dep` to Go modules and everything is building and passing tests. This particular error will be caused if you upgrade the `github.com/bdlm/errors` package beyond `v0.1.1`. Let me know if you need to use a newer version of the errors package and I will look at migrating this to it.
