### ISSUE TITLE
Question: How to get the current DOM at some point of time

### ISSUE THREAD

**Issue by alejoloaiza** [mkenney/go-chrome#90]
Hi, I want to know how can I print or get the DOM tree in some variable at some point of time, for example when page is loaded. thanks a lot. regards.

**Comment by mkenney** [comment]
Hi @alejoloaiza,

There are probably several ways to do that depending on what exactly you're trying to do. You could use a timer or page events or DOM events to trigger calling the DOM tree. There are also several ways to manipulate the DOM. The [devtools-protocol docs](https://chromedevtools.github.io/devtools-protocol/tot/DOM) are really the best reference to the API.

Something like this might help get you started. It uses a Page event to wait for the page to load and then captures the root [DOM node](https://chromedevtools.github.io/devtools-protocol/tot/DOM#type-Node):

```go
	// Enable Page events for this tab.
	if enableResult := <-tab.Page().Enable(); nil != enableResult.Err {
		panic(enableResult.Err)
	}

	// Enable the DOM agent for this tab.
	if enableResult := <-tab.DOM().Enable(); nil != enableResult.Err {
		panic(enableResult.Err)
	}

	// Create a channel to receive the DOM data.
	results := make(chan *dom.GetDocumentResult)

	// When the page load event fires, deliver the root DOM node.
	tab.Page().OnLoadEventFired(func(event *page.LoadEventFiredEvent) {
		results <- <-tab.DOM().GetDocument(&dom.GetDocumentParams{})
	})

	// Wait for the handler to fire
	domNode := <-results

	tmp, _ := json.MarshalIndent(domNode, "", "    ")
	fmt.Printf("DOM: %s\n\n", string(tmp))
```

**Comment by alejoloaiza** [comment]
Hi @mkenney Thanks for the quick reply, I will test it and let you know. regards.
